In [4]:
import pandas as pd  #pd is hust a alias
import numpy as np   #np as a alias

# Read Excel Sheet

In [5]:
df = pd.read_csv('Player.csv')    #

In [6]:
df  # store all the data into df variable

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
...,...,...,...,...,...,...,...,...
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

# Get Top 10 Records

In [7]:
df.head(10)
# index number is not in my excel sheet its generate automatically

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
5,6,R Dravid,11-Jan-73,Right_Hand,Right-arm offbreak,India,0,NaN
6,7,W Jaffer,16-Feb-78,Right_Hand,Right-arm offbreak,India,0,NaN
7,8,V Kohli,5-Nov-88,Right_Hand,Right-arm medium,India,0,NaN
8,9,JH Kallis,16-Oct-75,Right_Hand,Right-arm fast-medium,South Africa,0,NaN
9,10,CL White,18-Aug-83,Right_Hand,Legbreak googly,Australia,0,NaN

# Get last 10 records

In [8]:
df.tail(10)
# get last 10 record

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
513,514,I Shivram,NaN,NaN,NaN,India,1,NaN
514,515,SD Ranade,NaN,NaN,NaN,India,1,NaN
515,516,TH Wijewardene,NaN,NaN,NaN,Sri Lanka,1,NaN
516,517,AL Hill,NaN,NaN,NaN,New Zealand,1,NaN
517,518,RJ Tucker,NaN,NaN,NaN,Australia,1,NaN
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

# Get the data type of the DataFrame

In [9]:
type(df)

pandas.core.frame.DataFrame

# Get all The Columns

In [10]:
df.columns

Index(['Player_Id', 'Player_Name', 'DOB', 'Batting_Hand', 'Bowling_Skill',
       'Country', 'Is_Umpire', 'Unnamed: 7'],
      dtype='object')

In [11]:
df.tail()

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

# Store top 10 records into CSV Formet

In [12]:
df1 = df.head()

In [13]:
df1.to_csv('top10_records.csv')

# Read the save data

In [14]:
pd.read_csv('top10_records.csv')

,Unnamed: 0,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN

# Convert Column name into csv element

In [15]:
df = pd.read_csv('Player.csv',header = None)

In [16]:
df

,0,1,2,3,4,5,6,7
0,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,NaN
1,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
2,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
3,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
4,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
...,...,...,...,...,...,...,...,...
519,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
520,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
521,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
522,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
523,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

# Give my Own Columns name

In [17]:
df = pd.read_csv('Player.csv' , header = None , names = ['a'  , 'b' , 'c' , 'd', 'e' , 'f' , 'g' , 'h'])

In [18]:
df

,a,b,c,d,e,f,g,h
0,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,NaN
1,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
2,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
3,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
4,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
...,...,...,...,...,...,...,...,...
519,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
520,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
521,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
522,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
523,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

# Skiped Rows Data

In [19]:
df = pd.read_csv('Player.csv' , skiprows= [0,4,6,8])

In [20]:
df

,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,Unnamed: 7
0,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
1,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
2,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
3,7,W Jaffer,16-Feb-78,Right_Hand,Right-arm offbreak,India,0,NaN
4,9,JH Kallis,16-Oct-75,Right_Hand,Right-arm fast-medium,South Africa,0,NaN
...,...,...,...,...,...,...,...,...
514,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
515,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
516,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
517,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
518,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

# Where Value == 1 then Convert into NaN Value

In [21]:
df = pd.read_csv('Player.csv' , na_values= [1])

In [22]:
df

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,NaN,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0.0,NaN
1,2.0,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0.0,NaN
2,3.0,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0.0,NaN
3,4.0,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0.0,NaN
4,5.0,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0.0,NaN
...,...,...,...,...,...,...,...,...
518,519.0,Subroto Das,NaN,NaN,NaN,India,NaN,NaN
519,520.0,K Srinivasan,NaN,NaN,NaN,India,NaN,NaN
520,521.0,VK Sharma,NaN,NaN,NaN,India,NaN,NaN
521,523.0,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0.0,NaN
522,524.0,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0.0,NaN

# Where values == 'SC Ganguly' then Convert Into NaN

In [23]:
df = pd.read_csv('Player.csv' , na_values= 'SC Ganguly')
# you give multiple value seperated by , (comma) and it will converted

In [24]:
df

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,NaN,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
...,...,...,...,...,...,...,...,...
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [25]:
df = pd.read_csv('Player.csv')

# Get Stats of DataFrame

In [26]:
df.describe()

        Player_Id   Is_Umpire  Unnamed: 7
count  523.000000  523.000000   12.000000
mean   262.003824    0.099426    6.500000
std    151.127981    0.299520    3.605551
min      1.000000    0.000000    1.000000
25%    131.500000    0.000000    3.750000
50%    262.000000    0.000000    6.500000
75%    392.500000    0.000000    9.250000
max    524.000000    1.000000   12.000000

# Get all the columns DataType

In [27]:
df.dtypes

Player_Id          int64
Player_Name       object
DOB               object
Batting_Hand      object
Bowling_Skill     object
Country           object
Is_Umpire          int64
Unnamed: 7       float64
dtype: object

In [28]:
df = pd.read_csv('Player.csv')

In [29]:
df

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
...,...,...,...,...,...,...,...,...
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

# Remove Defualt Indexes

In [30]:
df2 = pd.read_csv('top10_records.csv')

In [31]:
df2.to_csv('top10_records.csv',index = False)

# Remove Column Name

In [32]:
df2.to_csv('top10_records.csv',header=False)

# all data Seperated By #

In [33]:
df2.to_csv('top10_records.csv',sep = '#')

# Store Only Two Columns

In [34]:
df2.to_csv('result3.csv',columns = ['Player_Id','DOB'])

In [35]:
df

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
...,...,...,...,...,...,...,...,...
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

# Slicing In DataFrame and Extract The Data

In [36]:
df.head()

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN

In [37]:
df.columns

Index(['Player_Id', 'Player_Name', 'DOB', 'Batting_Hand', 'Bowling_Skill',
       'Country', 'Is_Umpire', 'Unnamed: 7'],
      dtype='object')

In [38]:
df['Player_Id']

0        1
1        2
2        3
3        4
4        5
      ...
518    519
519    520
520    521
521    523
522    524
Name: Player_Id, Length: 523, dtype: int64

# Access Multiple Records

In [43]:
df[['Player_Id','Batting_Hand' , 'DOB']]

     Player_Id Batting_Hand        DOB
0            1    Left_Hand   8-Jul-72
1            2   Right_Hand  27-Sep-81
2            3   Right_Hand  19-Dec-74
3            4   Right_Hand  15-Jul-77
4            5   Right_Hand  17-Oct-80
..         ...          ...        ...
518        519          NaN        NaN
519        520          NaN        NaN
520        521          NaN        NaN
521        523   Right_Hand  14-Mar-92
522        524   Right_Hand   8-Jul-94

[523 rows x 3 columns]

In [44]:
df[['Is_Umpire','Player_Id','Batting_Hand']]

     Is_Umpire  Player_Id Batting_Hand
0            0          1    Left_Hand
1            0          2   Right_Hand
2            0          3   Right_Hand
3            0          4   Right_Hand
4            0          5   Right_Hand
..         ...        ...          ...
518          1        519          NaN
519          1        520          NaN
520          1        521          NaN
521          0        523   Right_Hand
522          0        524   Right_Hand

[523 rows x 3 columns]

# Convert Series Into DataFrame

In [40]:
df[['Player_Id']]

     Player_Id
0            1
1            2
2            3
3            4
4            5
..         ...
518        519
519        520
520        521
521        523
522        524

[523 rows x 1 columns]

# Series is nothing but one Single Record

In [39]:
type(df['Player_Id'])

pandas.core.series.Series

# Read Excel Sheet

In [ ]:
# pd.read_excel('execfile_name',sheet_name='adding_sheeet_name_as_samefile_name')

# Read Html Page

In [47]:
df4 = pd.read_html('https://www.basketball-reference.com/players/i/ibakase01.html')

In [48]:
df4

[       Season   Age   Tm                                       Lg  \
 0     2008-09  19.0  NaN    Did Not PlayÂ (other pro leagueâ€”Spain)
 1     2009-10  20.0  OKC                                      NBA
 2     2010-11  21.0  OKC                                      NBA
 3     2011-12  22.0  OKC                                      NBA
 4     2012-13  23.0  OKC                                      NBA
 5     2013-14  24.0  OKC                                      NBA
 6     2014-15  25.0  OKC                                      NBA
 7     2015-16  26.0  OKC                                      NBA
 8     2016-17  27.0  TOT                                      NBA
 9     2016-17  27.0  ORL                                      NBA
 10    2016-17  27.0  TOR                                      NBA
 11    2017-18  28.0  TOR                                      NBA
 12    2018-19  29.0  TOR                                      NBA
 13    2019-20  30.0  TOR                                      NBA
 14    2020-21  31.0  LAC                                      NBA
 15    2021-22  32.0  TOT                                      NBA
 16    2021-22  32.0  LAC                                      NBA
 17    2021-22  32.0  MIL                                      NBA
 18    2022-23  33.0  MIL                                      NBA
 19    2023-24  34.0  NaN  Did Not PlayÂ (other pro leagueâ€”Germany)
 20     Career   NaN  NaN                                      NBA
 21        NaN   NaN  NaN                                      NaN
 22  7 seasons   NaN  OKC                                      NBA
 23  4 seasons   NaN  TOR                                      NBA
 24  2 seasons   NaN  LAC                                      NBA
 25   1 season   NaN  ORL                                      NBA
 26  2 seasons   NaN  MIL                                      NBA

                                         Pos  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                        PF
 2                                        PF
 3                                        PF
 4                                        PF
 5                                        PF
 6                                        PF
 7                                        PF
 8                                        PF
 9                                        PF
 10                                       PF
 11                                       PF
 12                                        C
 13                                        C
 14                                        C
 15                                        C
 16                                        C
 17                                        C
 18                                        C
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                      NaN
 21                                      NaN
 22                                      NaN
 23                                      NaN
 24                                      NaN
 25                                      NaN
 26                                      NaN

                                           G  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                        73
 2                                        82
 3                                        66
 4                                        80
 5                                        81
 6                                        64
 7                                        78
 8                                        79
 9                                        56
 10                                       23
 11                                       76
 12                                       74
 13                                       55
 14                                       41
 15                                       54
 16                                       35
 17                                       19
 18                                       16
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                      919
 21                                      NaN
 22                                      524
 23                                      228
 24                                       76
 25                                       56
 26                                       35

                                          GS  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                         0
 2                                        44
 3                                        66
 4                                        80
 5                                        81
 6                                        64
 7                                        78
 8                                        79
 9                                        56
 10                                       23
 11                                       76
 12                                       51
 13                                       27
 14                                       39
 15                                       12
 16                                       10
 17                                        2
 18                                        0
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                      697
 21                                      NaN
 22                                      413
 23                                      177
 24                                       49
 25                                       56
 26                                        2

                                          MP  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                      18.1
 2                                      27.0
 3                                      27.2
 4                                      31.1
 5                                      32.9
 6                                      33.1
 7                                      32.1
 8                                      30.7
 9                                      30.5
 10                                     31.0
 11                                     27.5
 12                                     27.2
 13                                     27.0
 14                                     23.3
 15                                     16.3
 16                                     15.4
 17                                     17.8
 18                                     11.6
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                     27.3
 21                                      NaN
 22                                     28.8
 23                                     27.6
 24                                     19.6
 25                                     30.5
 26                                     15.0

                                          FG  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                       2.8
 2                                       4.1
 3                                       4.0
 4                                       5.6
 5                                       6.5
 6                                       5.8
 7                                       5.3
 8                                       6.0
 9                                       6.1
 10                                      5.6
 11                                      5.0
 12                                      6.3
 13                                      6.2
 14                                      4.5
 15                                      2.7
 16                                      2.7
 17                                      2.8
 18                                      1.6
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                      5.0
 21                                      NaN
 22                                      4.9
 23                                      5.8
 24                                      3.7
 25                                      6.1
 26                                      2.3

                                         FGA  ...  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)  ...
 1                                       5.1  ...
 2                                       7.5  ...
 3                                       7.4  ...
 4                                       9.7  ...
 5                                      12.1  ...
 6                                      12.3  ...
 7                                      11.1  ...
 8                                      12.4  ...
 9                                      12.6  ...
 10                                     12.1  ...
 11                                     10.3  ...
 12                                     11.9  ...
 13                                     12.2  ...
 14                                      8.9  ...
 15                                      5.5  ...
 16                                      5.5  ...
 17                                      5.5  ...
 18                                      3.4  ...
 19  Did Not PlayÂ (other pro leagueâ€”Germany)  ...
 20                                      9.7  ...
 21                                      NaN  ...
 22                                      9.3  ...
 23                                     11.4  ...
 24                                      7.3  ...
 25                                     12.6  ...
 26                                      4.5  ...

                                         DRB  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                       3.5
 2                                       5.0
 3                                       4.6
 4                                       4.9
 5                                       6.0
 6                                       5.7
 7                                       5.0
 8                                       5.2
 9                                       5.0
 10                                      5.5
 11                                      5.3
 12                                      6.0
 13                                      6.1
 14                                      4.9
 15                                      3.5
 16                                      3.1
 17                                      4.1
 18                                      1.8
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                      5.0
 21                                      NaN
 22                                      5.0
 23                                      5.7
 24                                      4.1
 25                                      5.0
 26                                      3.1

                                         TRB  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                       5.4
 2                                       7.6
 3                                       7.5
 4                                       7.7
 5                                       8.8
 6                                       7.8
 7                                       6.8
 8                                       6.8
 9                                       6.8
 10                                      6.8
 11                                      6.3
 12                                      8.1
 13                                      8.2
 14                                      6.7
 15                                      4.6
 16                                      4.3
 17                                      5.3
 18                                      2.8
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                      7.1
 21                                      NaN
 22                                      7.4
 23                                      7.4
 24                                      5.6
 25                                      6.8
 26                                      4.1

                                         AST  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                       0.1
 2                                       0.3
 3                                       0.4
 4                                       0.5
 5                                       1.0
 6                                       0.9
 7                                       0.8
 8                                       0.9
 9                                       1.1
 10                                      0.7
 11                                      0.8
 12                                      1.3
 13                                      1.4
 14                                      1.8
 15                                      0.9
 16                                      1.0
 17                                      0.7
 18                                      0.3
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                      0.8
 21                                      NaN
 22                                      0.6
 23                                      1.1
 24                                      1.4
 25                                      1.1
 26                                      0.5

                                         STL  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                       0.3
 2                                       0.4
 3                                       0.5
 4                                       0.4
 5                                       0.5
 6                                       0.5
 7                                       0.5
 8                                       0.5
 9                                       0.6
 10                                      0.3
 11                                      0.4
 12                                      0.4
 13                                      0.5
 14                                      0.2
 15                                      0.2
 16                                      0.2
 17                                      0.2
 18                                      0.1
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                      0.4
 21                                      NaN
 22                                      0.4
 23                                      0.4
 24                                      0.2
 25                                      0.6
 26                                      0.2

                                         BLK  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                       1.3
 2                                       2.4
 3                                       3.7
 4                                       3.0
 5                                       2.7
 6                                       2.4
 7                                       1.9
 8                                       1.6
 9                                       1.6
 10                                      1.4
 11                                      1.3
 12                                      1.4
 13                                      0.8
 14                                      1.1
 15                                      0.6
 16                                      0.7
 17                                      0.4
 18                                      0.4
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                      1.9
 21                                      NaN
 22                                      2.5
 23                                      1.2
 24                                      1.0
 25                                      1.6
 26                                      0.4

                                         TOV  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                       0.9
 2                                       0.9
 3                                       1.2
 4                                       1.6
 5                                       1.5
 6                                       1.5
 7                                       1.4
 8                                       1.3
 9                                       1.2
 10                                      1.7
 11                                      1.2
 12                                      1.5
 13                                      2.0
 14                                      1.1
 15                                      0.8
 16                                      0.9
 17                                      0.5
 18                                      0.7
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                      1.3
 21                                      NaN
 22                                      1.3
 23                                      1.5
 24                                      1.0
 25                                      1.2
 26                                      0.6

                                          PF  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                       2.7
 2                                       3.3
 3                                       2.7
 4                                       2.7
 5                                       2.9
 6                                       3.0
 7                                       2.7
 8                                       2.7
 9                                       2.5
 10                                      3.3
 11                                      2.8
 12                                      2.9
 13                                      2.8
 14                                      1.9
 15                                      1.9
 16                                      1.6
 17                                      2.4
 18                                      1.4
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                      2.7
 21                                      NaN
 22                                      2.8
 23                                      2.8
 24                                      1.7
 25                                      2.5
 26                                      2.0

                                         PTS  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                       6.3
 2                                       9.9
 3                                       9.1
 4                                      13.2
 5                                      15.1
 6                                      14.3
 7                                      12.6
 8                                      14.8
 9                                      15.1
 10                                     14.2
 11                                     12.6
 12                                     15.0
 13                                     15.4
 14                                     11.1
 15                                      6.8
 16                                      6.6
 17                                      7.0
 18                                      4.1
 19  Did Not PlayÂ (other pro leagueâ€”Germany)
 20                                     12.0
 21                                      NaN
 22                                     11.6
 23                                     14.2
 24                                      9.0
 25                                     15.1
 26                                      5.7

                                      Awards  \
 0     Did Not PlayÂ (other pro leagueâ€”Spain)
 1                                       NaN
 2                            DPOY-14,MIP-17

# type Of this data

In [49]:
type(df4)

list

# Get How Many Tables We Have

In [50]:
len(df4)

7

# Get the Table Data

In [53]:
df4[0]

,Season,Age,Tm,Lg,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Unnamed: 31
0,2008-09,19.0,NaN,Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),...,Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain),Did Not PlayÂ (other pro leagueâ€”Spain)
1,2009-10,20.0,OKC,NBA,PF,73,0,18.1,2.8,5.1,...,3.5,5.4,0.1,0.3,1.3,0.9,2.7,6.3,NaN,NaN
2,2010-11,21.0,OKC,NBA,PF,82,44,27.0,4.1,7.5,...,5.0,7.6,0.3,0.4,2.4,0.9,3.3,9.9,"DPOY-14,MIP-17",NaN
3,2011-12,22.0,OKC,NBA,PF,66,66,27.2,4.0,7.4,...,4.6,7.5,0.4,0.5,3.7,1.2,2.7,9.1,"DEF1,DPOY-2,MIP-11",NaN
4,2012-13,23.0,OKC,NBA,PF,80,80,31.1,5.6,9.7,...,4.9,7.7,0.5,0.4,3.0,1.6,2.7,13.2,"DEF1,DPOY-3,MIP-9",NaN
5,2013-14,24.0,OKC,NBA,PF,81,81,32.9,6.5,12.1,...,6.0,8.8,1.0,0.5,2.7,1.5,2.9,15.1,"DEF1,DPOY-4",NaN
6,2014-15,25.0,OKC,NBA,PF,64,64,33.1,5.8,12.3,...,5.7,7.8,0.9,0.5,2.4,1.5,3.0,14.3,NaN,NaN
7,2015-16,26.0,OKC,NBA,PF,78,78,32.1,5.3,11.1,...,5.0,6.8,0.8,0.5,1.9,1.4,2.7,12.6,NaN,NaN
8,2016-17,27.0,TOT,NBA,PF,79,79,30.7,6.0,12.4,...,5.2,6.8,0.9,0.5,1.6,1.3,2.7,14.8,NaN,NaN
9,2016-17,27.0,ORL,NBA,PF,56,56,30.5,6.1,12.6,...,5.0,6.8,1.1,0.6,1.6,1.2,2.5,15.1,NaN,NaN
10,2016-17,27.0,TOR,NBA,PF,23,23,31.0,5.6,12.1,...,5.5,6.8,0.7,0.3,1.4,1.7,3.3,14.2,NaN,NaN
11,2017-18,28.0,TOR,NBA,PF,76,76,27.5,5.0,10.3,...,5.3,6.3,0.8,0.4,1.3,1.2,2.8,12.6,NaN,NaN
12,2018-19,29.0,TOR,NBA,C,74,51,27.2,6.3,11.9,...,6.0,8.1,1.3,0.4,1.4,1.5,2.9,15.0,NaN,NaN
13,2019-20,30.0,TOR,NBA,C,55,27,27.0,6.2,12.2,...,6.1,8.2,1.4,0.5,0.8,2.0,2.8,15.4,NaN,NaN
14,2020-21,31.0,LAC,NBA,C,41,39,23.3,4.5,8.9,...,4.9,6.7,1.8,0.2,1.1,1.1,1.9,11.1,NaN,NaN
15,2021-22,32.0,TOT,NBA,C,54,12,16.3,2.7,5.5,...,3.5,4.6,0.9,0.2,0.6,0.8,1.9,6.8,NaN,NaN
16,2021-22,32.0,LAC,NBA,C,35,10,15.4,2.7,5.5,...,3.1,4.3,1.0,0.2,0.7,0.9,1.6,6.6,NaN,NaN
17,2021-22,32.0,MIL,NBA,C,19,2,17.8,2.8,5.5,...,4.1,5.3,0.7,0.2,0.4,0.5,2.4,7.0,NaN,NaN
18,2022-23,33.0,MIL,NBA,C,16,0,11.6,1.6,3.4,...,1.8,2.8,0.3,0.1,0.4,0.7,1.4,4.1,NaN,NaN
19,2023-24,34.0,NaN,Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),...,Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany),Did Not PlayÂ (other pro leagueâ€”Germany)
20,Career,NaN,NaN,NBA,NaN,919,697,27.3,5.0,9.7,...,5.0,7.1,0.8,0.4,1.9,1.3,2.7,12.0,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,7 seasons,NaN,OKC,NBA,NaN,524,413,28.8,4.9,9.3,...,5.0,7.4,0.6,0.4,2.5,1.3,2.8,11.6,NaN,NaN
23,4 seasons,NaN,TOR,NBA,NaN,228,177,27.6,5.8,11.4,...,5.7,7.4,1.1,0.4,1.2,1.5,2.8,14.2,NaN,NaN
24,2 seasons,NaN,LAC,NBA,NaN,76,49,19.6,3.7,7.3,...,4.1,5.6,1.4,0.2,1.0,1.0,1.7,9.0,NaN,NaN
25,1 season,NaN,ORL,NBA,NaN,56,56,30.5,6.1,12.6,...,5.0,6.8,1.1,0.6,1.6,1.2,2.5,15.1,NaN,NaN
26,2 seasons,NaN,MIL,NBA,NaN,35,2,15.0,2.3,4.5,...,3.1,4.1,0.5,0.2,0.4,0.6,2.0,5.7,NaN,NaN

In [55]:
df4[1]

,Season,Age,Tm,Lg,Pos,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2009-10,20.0,OKC,NBA,PF,6.0,0.0,25.5,3.3,5.8,...,0.700,2.2,4.3,6.5,0.3,0.3,2.0,1.0,3.2,7.8
1,2010-11,21.0,OKC,NBA,PF,17.0,17.0,28.8,3.9,8.5,...,0.825,2.8,4.5,7.3,0.2,0.2,3.1,1.2,3.8,9.8
2,2011-12,22.0,OKC,NBA,PF,20.0,20.0,28.5,4.2,8.0,...,0.722,2.4,3.4,5.8,0.6,0.6,3.0,0.6,2.9,9.8
3,2012-13,23.0,OKC,NBA,PF,11.0,11.0,33.3,5.4,12.3,...,0.792,3.5,4.8,8.4,0.7,0.0,3.0,0.6,3.5,12.8
4,2013-14,24.0,OKC,NBA,PF,17.0,17.0,34.2,5.1,8.6,...,0.765,1.8,5.0,6.8,0.7,0.6,2.5,1.2,3.2,12.1
5,2015-16,26.0,OKC,NBA,PF,18.0,18.0,33.4,4.7,9.1,...,0.750,1.3,5.0,6.3,0.6,0.8,1.3,0.5,2.8,12.0
6,2016-17,27.0,TOR,NBA,PF,10.0,10.0,30.7,6.0,13.0,...,0.846,0.9,5.6,6.5,1.4,0.4,1.7,1.1,3.7,14.3
7,2017-18,28.0,TOR,NBA,PF,10.0,9.0,26.0,3.0,7.2,...,0.818,1.3,4.6,5.9,1.1,0.1,1.3,1.6,2.1,8.7
8,2018-19,29.0,TOR,NBA,C,24.0,0.0,20.8,3.8,8.0,...,0.762,1.5,4.5,6.0,0.9,0.5,1.0,1.0,3.3,9.4
9,2019-20,30.0,TOR,NBA,C,11.0,0.0,22.8,5.7,10.0,...,1.000,1.5,6.2,7.7,1.2,0.2,1.3,1.1,2.5,14.8
10,2020-21,31.0,LAC,NBA,C,2.0,0.0,9.0,1.5,3.0,...,1.000,0.5,1.5,2.0,1.0,0.5,1.5,0.5,0.5,5.0
11,2021-22,32.0,MIL,NBA,C,6.0,0.0,3.7,0.7,2.7,...,0.500,0.3,1.3,1.7,0.0,0.0,0.0,0.3,0.2,1.5
12,Career,NaN,NaN,NBA,NaN,152.0,102.0,27.1,4.3,8.6,...,0.789,1.8,4.5,6.3,0.7,0.4,1.9,0.9,3.0,10.6
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,6 seasons,NaN,OKC,NBA,NaN,89.0,83.0,31.0,4.5,8.8,...,0.768,2.2,4.5,6.7,0.5,0.5,2.5,0.8,3.2,10.9
15,4 seasons,NaN,TOR,NBA,NaN,55.0,19.0,24.0,4.5,9.2,...,0.824,1.3,5.1,6.4,1.1,0.3,1.2,1.2,3.0,11.2
16,1 season,NaN,MIL,NBA,NaN,6.0,0.0,3.7,0.7,2.7,...,0.500,0.3,1.3,1.7,0.0,0.0,0.0,0.3,0.2,1.5
17,1 season,NaN,LAC,NBA,NaN,2.0,0.0,9.0,1.5,3.0,...,1.000,0.5,1.5,2.0,1.0,0.5,1.5,0.5,0.5,5.0

In [56]:
df4[2]

                 Highlight  Unnamed: 1                        In Stathead
0      Career high, Points        34.0  View full stats from top 20 games
1    Career high, Rebounds        22.0  View full stats from top 20 games
2     Career high, Assists         6.0  View full stats from top 20 games
3      Career high, Steals         3.0  View full stats from top 20 games
4      Career high, Blocks        11.0  View full stats from top 20 games
5  Career high, Game Score        33.1  View full stats from top 20 games
6           Triple-Doubles         1.0                           View all

In [57]:
df4[3]

,Season,Age,Tm,Lg,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Unnamed: 30,Trp-Dbl
0,2009-10,20.0,OKC,NBA,PF,73.0,0.0,1323.0,201.0,370.0,...,259.0,397.0,10.0,25.0,97.0,68.0,194.0,461.0,NaN,0.0
1,2010-11,21.0,OKC,NBA,PF,82.0,44.0,2216.0,335.0,617.0,...,408.0,622.0,22.0,31.0,198.0,71.0,267.0,808.0,NaN,0.0
2,2011-12,22.0,OKC,NBA,PF,66.0,66.0,1792.0,262.0,490.0,...,305.0,498.0,28.0,33.0,241.0,79.0,179.0,603.0,NaN,1.0
3,2012-13,23.0,OKC,NBA,PF,80.0,80.0,2486.0,446.0,778.0,...,395.0,617.0,43.0,28.0,242.0,125.0,213.0,1055.0,NaN,0.0
4,2013-14,24.0,OKC,NBA,PF,81.0,81.0,2666.0,524.0,978.0,...,485.0,709.0,85.0,39.0,219.0,123.0,233.0,1227.0,NaN,0.0
5,2014-15,25.0,OKC,NBA,PF,64.0,64.0,2116.0,374.0,786.0,...,364.0,499.0,55.0,30.0,155.0,97.0,194.0,917.0,NaN,0.0
6,2015-16,26.0,OKC,NBA,PF,78.0,78.0,2500.0,416.0,869.0,...,392.0,533.0,66.0,38.0,148.0,108.0,211.0,983.0,NaN,0.0
7,2016-17,27.0,TOT,NBA,PF,79.0,79.0,2422.0,471.0,982.0,...,409.0,538.0,75.0,41.0,124.0,105.0,215.0,1173.0,NaN,0.0
8,2016-17,27.0,ORL,NBA,PF,56.0,56.0,1710.0,343.0,703.0,...,282.0,382.0,60.0,34.0,91.0,66.0,139.0,846.0,NaN,0.0
9,2016-17,27.0,TOR,NBA,PF,23.0,23.0,712.0,128.0,279.0,...,127.0,156.0,15.0,7.0,33.0,39.0,76.0,327.0,NaN,0.0
10,2017-18,28.0,TOR,NBA,PF,76.0,76.0,2093.0,379.0,784.0,...,400.0,478.0,62.0,29.0,99.0,90.0,209.0,959.0,NaN,0.0
11,2018-19,29.0,TOR,NBA,C,74.0,51.0,2010.0,464.0,877.0,...,445.0,601.0,99.0,29.0,103.0,114.0,211.0,1112.0,NaN,0.0
12,2019-20,30.0,TOR,NBA,C,55.0,27.0,1485.0,343.0,670.0,...,338.0,452.0,77.0,28.0,46.0,109.0,153.0,845.0,NaN,0.0
13,2020-21,31.0,LAC,NBA,C,41.0,39.0,955.0,186.0,365.0,...,202.0,275.0,74.0,9.0,47.0,44.0,76.0,454.0,NaN,0.0
14,2021-22,32.0,TOT,NBA,C,54.0,12.0,878.0,148.0,296.0,...,188.0,250.0,49.0,11.0,33.0,43.0,102.0,365.0,NaN,0.0
15,2021-22,32.0,LAC,NBA,C,35.0,10.0,538.0,94.0,192.0,...,110.0,150.0,36.0,7.0,26.0,33.0,56.0,232.0,NaN,0.0
16,2021-22,32.0,MIL,NBA,C,19.0,2.0,339.0,54.0,104.0,...,78.0,100.0,13.0,4.0,7.0,10.0,46.0,133.0,NaN,0.0
17,2022-23,33.0,MIL,NBA,C,16.0,0.0,185.0,26.0,54.0,...,29.0,44.0,4.0,2.0,7.0,11.0,23.0,66.0,NaN,0.0
18,Career,NaN,NaN,NBA,NaN,919.0,697.0,25127.0,4575.0,8916.0,...,4619.0,6513.0,749.0,373.0,1759.0,1187.0,2480.0,11028.0,NaN,1.0
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,7 seasons,NaN,OKC,NBA,NaN,524.0,413.0,15099.0,2558.0,4888.0,...,2608.0,3875.0,309.0,224.0,1300.0,671.0,1491.0,6054.0,NaN,1.0
21,4 seasons,NaN,TOR,NBA,NaN,228.0,177.0,6300.0,1314.0,2610.0,...,1310.0,1687.0,253.0,93.0,281.0,352.0,649.0,3243.0,NaN,0.0
22,2 seasons,NaN,LAC,NBA,NaN,76.0,49.0,1493.0,280.0,557.0,...,312.0,425.0,110.0,16.0,73.0,77.0,132.0,686.0,NaN,0.0
23,1 season,NaN,ORL,NBA,NaN,56.0,56.0,1710.0,343.0,703.0,...,282.0,382.0,60.0,34.0,91.0,66.0,139.0,846.0,NaN,0.0
24,2 seasons,NaN,MIL,NBA,NaN,35.0,2.0,524.0,80.0,158.0,...,107.0,144.0,17.0,6.0,14.0,21.0,69.0,199.0,NaN,0.0

In [59]:
df4[4]

,Season,Age,Tm,Lg,Pos,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2009-10,20.0,OKC,NBA,PF,6.0,0.0,153.0,20.0,35.0,...,0.700,13.0,26.0,39.0,2.0,2.0,12.0,6.0,19.0,47.0
1,2010-11,21.0,OKC,NBA,PF,17.0,17.0,490.0,67.0,145.0,...,0.825,47.0,77.0,124.0,3.0,4.0,52.0,21.0,64.0,167.0
2,2011-12,22.0,OKC,NBA,PF,20.0,20.0,569.0,84.0,159.0,...,0.722,47.0,68.0,115.0,12.0,11.0,59.0,11.0,57.0,195.0
3,2012-13,23.0,OKC,NBA,PF,11.0,11.0,366.0,59.0,135.0,...,0.792,39.0,53.0,92.0,8.0,0.0,33.0,7.0,38.0,141.0
4,2013-14,24.0,OKC,NBA,PF,17.0,17.0,581.0,87.0,147.0,...,0.765,31.0,85.0,116.0,12.0,11.0,42.0,20.0,54.0,205.0
5,2015-16,26.0,OKC,NBA,PF,18.0,18.0,602.0,85.0,163.0,...,0.750,23.0,90.0,113.0,10.0,14.0,24.0,9.0,51.0,216.0
6,2016-17,27.0,TOR,NBA,PF,10.0,10.0,307.0,60.0,130.0,...,0.846,9.0,56.0,65.0,14.0,4.0,17.0,11.0,37.0,143.0
7,2017-18,28.0,TOR,NBA,PF,10.0,9.0,260.0,30.0,72.0,...,0.818,13.0,46.0,59.0,11.0,1.0,13.0,16.0,21.0,87.0
8,2018-19,29.0,TOR,NBA,C,24.0,0.0,500.0,92.0,193.0,...,0.762,35.0,108.0,143.0,22.0,11.0,23.0,25.0,79.0,225.0
9,2019-20,30.0,TOR,NBA,C,11.0,0.0,251.0,63.0,110.0,...,1.000,17.0,68.0,85.0,13.0,2.0,14.0,12.0,27.0,163.0
10,2020-21,31.0,LAC,NBA,C,2.0,0.0,18.0,3.0,6.0,...,1.000,1.0,3.0,4.0,2.0,1.0,3.0,1.0,1.0,10.0
11,2021-22,32.0,MIL,NBA,C,6.0,0.0,22.0,4.0,16.0,...,0.500,2.0,8.0,10.0,0.0,0.0,0.0,2.0,1.0,9.0
12,Career,NaN,NaN,NBA,NaN,152.0,102.0,4119.0,654.0,1311.0,...,0.789,277.0,688.0,965.0,109.0,61.0,292.0,141.0,449.0,1608.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,6 seasons,NaN,OKC,NBA,NaN,89.0,83.0,2761.0,402.0,784.0,...,0.768,200.0,399.0,599.0,47.0,42.0,222.0,74.0,283.0,971.0
15,4 seasons,NaN,TOR,NBA,NaN,55.0,19.0,1318.0,245.0,505.0,...,0.824,74.0,278.0,352.0,60.0,18.0,67.0,64.0,164.0,618.0
16,1 season,NaN,MIL,NBA,NaN,6.0,0.0,22.0,4.0,16.0,...,0.500,2.0,8.0,10.0,0.0,0.0,0.0,2.0,1.0,9.0
17,1 season,NaN,LAC,NBA,NaN,2.0,0.0,18.0,3.0,6.0,...,1.000,1.0,3.0,4.0,2.0,1.0,3.0,1.0,1.0,10.0

In [60]:
df4[5]

,Season,Age,Tm,Lg,Pos,G,MP,PER,TS%,3PAr,...,Unnamed: 19,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP
0,2009-10,20.0,OKC,NBA,PF,73.0,1323.0,15.2,0.562,0.005,...,NaN,1.3,2.4,3.7,0.134,NaN,-2.4,0.9,-1.5,0.2
1,2010-11,21.0,OKC,NBA,PF,82.0,2216.0,17.7,0.579,0.002,...,NaN,4.3,3.2,7.6,0.164,NaN,-0.2,0.7,0.5,1.4
2,2011-12,22.0,OKC,NBA,PF,66.0,1792.0,19.0,0.556,0.006,...,NaN,3.0,3.2,6.2,0.167,NaN,0.1,2.3,2.3,1.9
3,2012-13,23.0,OKC,NBA,PF,80.0,2486.0,19.4,0.612,0.073,...,NaN,5.3,4.1,9.4,0.181,NaN,0.9,0.7,1.5,2.2
4,2013-14,24.0,OKC,NBA,PF,81.0,2666.0,19.6,0.576,0.061,...,NaN,5.2,4.4,9.6,0.173,NaN,1.1,0.6,1.7,2.5
5,2014-15,25.0,OKC,NBA,PF,64.0,2116.0,16.6,0.549,0.261,...,NaN,2.9,2.7,5.6,0.127,NaN,0.5,0.4,0.9,1.6
6,2015-16,26.0,OKC,NBA,PF,78.0,2500.0,13.9,0.533,0.212,...,NaN,2.5,3.0,5.5,0.105,NaN,-0.6,0.0,-0.6,0.8
7,2016-17,27.0,TOT,NBA,PF,79.0,2422.0,16.4,0.566,0.323,...,NaN,2.5,2.6,5.1,0.101,NaN,0.4,-0.3,0.1,1.2
8,2016-17,27.0,ORL,NBA,PF,56.0,1710.0,17.5,0.569,0.304,...,NaN,2.1,1.7,3.8,0.108,NaN,0.9,-0.2,0.7,1.2
9,2016-17,27.0,TOR,NBA,PF,23.0,712.0,13.8,0.556,0.369,...,NaN,0.4,0.8,1.3,0.085,NaN,-0.8,-0.6,-1.5,0.1
10,2017-18,28.0,TOR,NBA,PF,76.0,2093.0,14.7,0.574,0.379,...,NaN,2.1,3.0,5.1,0.117,NaN,-0.1,0.0,-0.1,1.0
11,2018-19,29.0,TOR,NBA,C,74.0,2010.0,18.7,0.582,0.193,...,NaN,2.8,3.3,6.1,0.146,NaN,0.2,0.1,0.2,1.2
12,2019-20,30.0,TOR,NBA,C,55.0,1485.0,17.3,0.583,0.272,...,NaN,1.2,2.7,3.9,0.126,NaN,0.1,0.0,0.1,0.8
13,2020-21,31.0,LAC,NBA,C,41.0,955.0,18.2,0.585,0.315,...,NaN,1.7,1.3,3.0,0.150,NaN,1.2,0.2,1.4,0.8
14,2021-22,32.0,TOT,NBA,C,54.0,878.0,14.4,0.579,0.334,...,NaN,0.8,1.1,2.0,0.108,NaN,-1.3,-0.2,-1.5,0.1
15,2021-22,32.0,LAC,NBA,C,35.0,538.0,14.9,0.567,0.323,...,NaN,0.3,0.8,1.1,0.096,NaN,-1.3,0.3,-1.0,0.1
16,2021-22,32.0,MIL,NBA,C,19.0,339.0,13.7,0.601,0.356,...,NaN,0.5,0.4,0.9,0.128,NaN,-1.4,-1.0,-2.4,0.0
17,2022-23,33.0,MIL,NBA,C,16.0,185.0,9.8,0.553,0.333,...,NaN,0.0,0.2,0.2,0.058,NaN,-4.6,0.0,-4.5,-0.1
18,Career,NaN,NaN,NBA,NaN,919.0,25127.0,17.1,0.571,0.192,...,NaN,35.7,37.3,73.0,0.139,NaN,0.1,0.4,0.5,15.7
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,7 seasons,NaN,OKC,NBA,NaN,524.0,15099.0,17.5,0.567,0.105,...,NaN,24.5,23.1,47.6,0.151,NaN,0.1,0.7,0.8,10.7
21,4 seasons,NaN,TOR,NBA,NaN,228.0,6300.0,16.5,0.577,0.288,...,NaN,6.6,9.8,16.4,0.125,NaN,-0.1,0.0,-0.1,3.1
22,2 seasons,NaN,LAC,NBA,NaN,76.0,1493.0,17.0,0.578,0.318,...,NaN,2.0,2.0,4.1,0.130,NaN,0.3,0.2,0.6,1.0
23,1 season,NaN,ORL,NBA,NaN,56.0,1710.0,17.5,0.569,0.304,...,NaN,2.1,1.7,3.8,0.108,NaN,0.9,-0.2,0.7,1.2
24,2 seasons,NaN,MIL,NBA,NaN,35.0,524.0,12.4,0.584,0.348,...,NaN,0.5,0.6,1.1,0.103,NaN,-2.5,-0.7,-3.2,-0.2

In [61]:

df4[5]

,Season,Age,Tm,Lg,Pos,G,MP,PER,TS%,3PAr,...,Unnamed: 19,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP
0,2009-10,20.0,OKC,NBA,PF,73.0,1323.0,15.2,0.562,0.005,...,NaN,1.3,2.4,3.7,0.134,NaN,-2.4,0.9,-1.5,0.2
1,2010-11,21.0,OKC,NBA,PF,82.0,2216.0,17.7,0.579,0.002,...,NaN,4.3,3.2,7.6,0.164,NaN,-0.2,0.7,0.5,1.4
2,2011-12,22.0,OKC,NBA,PF,66.0,1792.0,19.0,0.556,0.006,...,NaN,3.0,3.2,6.2,0.167,NaN,0.1,2.3,2.3,1.9
3,2012-13,23.0,OKC,NBA,PF,80.0,2486.0,19.4,0.612,0.073,...,NaN,5.3,4.1,9.4,0.181,NaN,0.9,0.7,1.5,2.2
4,2013-14,24.0,OKC,NBA,PF,81.0,2666.0,19.6,0.576,0.061,...,NaN,5.2,4.4,9.6,0.173,NaN,1.1,0.6,1.7,2.5
5,2014-15,25.0,OKC,NBA,PF,64.0,2116.0,16.6,0.549,0.261,...,NaN,2.9,2.7,5.6,0.127,NaN,0.5,0.4,0.9,1.6
6,2015-16,26.0,OKC,NBA,PF,78.0,2500.0,13.9,0.533,0.212,...,NaN,2.5,3.0,5.5,0.105,NaN,-0.6,0.0,-0.6,0.8
7,2016-17,27.0,TOT,NBA,PF,79.0,2422.0,16.4,0.566,0.323,...,NaN,2.5,2.6,5.1,0.101,NaN,0.4,-0.3,0.1,1.2
8,2016-17,27.0,ORL,NBA,PF,56.0,1710.0,17.5,0.569,0.304,...,NaN,2.1,1.7,3.8,0.108,NaN,0.9,-0.2,0.7,1.2
9,2016-17,27.0,TOR,NBA,PF,23.0,712.0,13.8,0.556,0.369,...,NaN,0.4,0.8,1.3,0.085,NaN,-0.8,-0.6,-1.5,0.1
10,2017-18,28.0,TOR,NBA,PF,76.0,2093.0,14.7,0.574,0.379,...,NaN,2.1,3.0,5.1,0.117,NaN,-0.1,0.0,-0.1,1.0
11,2018-19,29.0,TOR,NBA,C,74.0,2010.0,18.7,0.582,0.193,...,NaN,2.8,3.3,6.1,0.146,NaN,0.2,0.1,0.2,1.2
12,2019-20,30.0,TOR,NBA,C,55.0,1485.0,17.3,0.583,0.272,...,NaN,1.2,2.7,3.9,0.126,NaN,0.1,0.0,0.1,0.8
13,2020-21,31.0,LAC,NBA,C,41.0,955.0,18.2,0.585,0.315,...,NaN,1.7,1.3,3.0,0.150,NaN,1.2,0.2,1.4,0.8
14,2021-22,32.0,TOT,NBA,C,54.0,878.0,14.4,0.579,0.334,...,NaN,0.8,1.1,2.0,0.108,NaN,-1.3,-0.2,-1.5,0.1
15,2021-22,32.0,LAC,NBA,C,35.0,538.0,14.9,0.567,0.323,...,NaN,0.3,0.8,1.1,0.096,NaN,-1.3,0.3,-1.0,0.1
16,2021-22,32.0,MIL,NBA,C,19.0,339.0,13.7,0.601,0.356,...,NaN,0.5,0.4,0.9,0.128,NaN,-1.4,-1.0,-2.4,0.0
17,2022-23,33.0,MIL,NBA,C,16.0,185.0,9.8,0.553,0.333,...,NaN,0.0,0.2,0.2,0.058,NaN,-4.6,0.0,-4.5,-0.1
18,Career,NaN,NaN,NBA,NaN,919.0,25127.0,17.1,0.571,0.192,...,NaN,35.7,37.3,73.0,0.139,NaN,0.1,0.4,0.5,15.7
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,7 seasons,NaN,OKC,NBA,NaN,524.0,15099.0,17.5,0.567,0.105,...,NaN,24.5,23.1,47.6,0.151,NaN,0.1,0.7,0.8,10.7
21,4 seasons,NaN,TOR,NBA,NaN,228.0,6300.0,16.5,0.577,0.288,...,NaN,6.6,9.8,16.4,0.125,NaN,-0.1,0.0,-0.1,3.1
22,2 seasons,NaN,LAC,NBA,NaN,76.0,1493.0,17.0,0.578,0.318,...,NaN,2.0,2.0,4.1,0.130,NaN,0.3,0.2,0.6,1.0
23,1 season,NaN,ORL,NBA,NaN,56.0,1710.0,17.5,0.569,0.304,...,NaN,2.1,1.7,3.8,0.108,NaN,0.9,-0.2,0.7,1.2
24,2 seasons,NaN,MIL,NBA,NaN,35.0,524.0,12.4,0.584,0.348,...,NaN,0.5,0.6,1.1,0.103,NaN,-2.5,-0.7,-3.2,-0.2

In [62]:

df4[5]

,Season,Age,Tm,Lg,Pos,G,MP,PER,TS%,3PAr,...,Unnamed: 19,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP
0,2009-10,20.0,OKC,NBA,PF,73.0,1323.0,15.2,0.562,0.005,...,NaN,1.3,2.4,3.7,0.134,NaN,-2.4,0.9,-1.5,0.2
1,2010-11,21.0,OKC,NBA,PF,82.0,2216.0,17.7,0.579,0.002,...,NaN,4.3,3.2,7.6,0.164,NaN,-0.2,0.7,0.5,1.4
2,2011-12,22.0,OKC,NBA,PF,66.0,1792.0,19.0,0.556,0.006,...,NaN,3.0,3.2,6.2,0.167,NaN,0.1,2.3,2.3,1.9
3,2012-13,23.0,OKC,NBA,PF,80.0,2486.0,19.4,0.612,0.073,...,NaN,5.3,4.1,9.4,0.181,NaN,0.9,0.7,1.5,2.2
4,2013-14,24.0,OKC,NBA,PF,81.0,2666.0,19.6,0.576,0.061,...,NaN,5.2,4.4,9.6,0.173,NaN,1.1,0.6,1.7,2.5
5,2014-15,25.0,OKC,NBA,PF,64.0,2116.0,16.6,0.549,0.261,...,NaN,2.9,2.7,5.6,0.127,NaN,0.5,0.4,0.9,1.6
6,2015-16,26.0,OKC,NBA,PF,78.0,2500.0,13.9,0.533,0.212,...,NaN,2.5,3.0,5.5,0.105,NaN,-0.6,0.0,-0.6,0.8
7,2016-17,27.0,TOT,NBA,PF,79.0,2422.0,16.4,0.566,0.323,...,NaN,2.5,2.6,5.1,0.101,NaN,0.4,-0.3,0.1,1.2
8,2016-17,27.0,ORL,NBA,PF,56.0,1710.0,17.5,0.569,0.304,...,NaN,2.1,1.7,3.8,0.108,NaN,0.9,-0.2,0.7,1.2
9,2016-17,27.0,TOR,NBA,PF,23.0,712.0,13.8,0.556,0.369,...,NaN,0.4,0.8,1.3,0.085,NaN,-0.8,-0.6,-1.5,0.1
10,2017-18,28.0,TOR,NBA,PF,76.0,2093.0,14.7,0.574,0.379,...,NaN,2.1,3.0,5.1,0.117,NaN,-0.1,0.0,-0.1,1.0
11,2018-19,29.0,TOR,NBA,C,74.0,2010.0,18.7,0.582,0.193,...,NaN,2.8,3.3,6.1,0.146,NaN,0.2,0.1,0.2,1.2
12,2019-20,30.0,TOR,NBA,C,55.0,1485.0,17.3,0.583,0.272,...,NaN,1.2,2.7,3.9,0.126,NaN,0.1,0.0,0.1,0.8
13,2020-21,31.0,LAC,NBA,C,41.0,955.0,18.2,0.585,0.315,...,NaN,1.7,1.3,3.0,0.150,NaN,1.2,0.2,1.4,0.8
14,2021-22,32.0,TOT,NBA,C,54.0,878.0,14.4,0.579,0.334,...,NaN,0.8,1.1,2.0,0.108,NaN,-1.3,-0.2,-1.5,0.1
15,2021-22,32.0,LAC,NBA,C,35.0,538.0,14.9,0.567,0.323,...,NaN,0.3,0.8,1.1,0.096,NaN,-1.3,0.3,-1.0,0.1
16,2021-22,32.0,MIL,NBA,C,19.0,339.0,13.7,0.601,0.356,...,NaN,0.5,0.4,0.9,0.128,NaN,-1.4,-1.0,-2.4,0.0
17,2022-23,33.0,MIL,NBA,C,16.0,185.0,9.8,0.553,0.333,...,NaN,0.0,0.2,0.2,0.058,NaN,-4.6,0.0,-4.5,-0.1
18,Career,NaN,NaN,NBA,NaN,919.0,25127.0,17.1,0.571,0.192,...,NaN,35.7,37.3,73.0,0.139,NaN,0.1,0.4,0.5,15.7
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,7 seasons,NaN,OKC,NBA,NaN,524.0,15099.0,17.5,0.567,0.105,...,NaN,24.5,23.1,47.6,0.151,NaN,0.1,0.7,0.8,10.7
21,4 seasons,NaN,TOR,NBA,NaN,228.0,6300.0,16.5,0.577,0.288,...,NaN,6.6,9.8,16.4,0.125,NaN,-0.1,0.0,-0.1,3.1
22,2 seasons,NaN,LAC,NBA,NaN,76.0,1493.0,17.0,0.578,0.318,...,NaN,2.0,2.0,4.1,0.130,NaN,0.3,0.2,0.6,1.0
23,1 season,NaN,ORL,NBA,NaN,56.0,1710.0,17.5,0.569,0.304,...,NaN,2.1,1.7,3.8,0.108,NaN,0.9,-0.2,0.7,1.2
24,2 seasons,NaN,MIL,NBA,NaN,35.0,524.0,12.4,0.584,0.348,...,NaN,0.5,0.6,1.1,0.103,NaN,-2.5,-0.7,-3.2,-0.2

In [63]:
df4[6]

,Season,Age,Tm,Lg,Pos,G,MP,PER,TS%,3PAr,...,Unnamed: 19,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP
0,2009-10,20.0,OKC,NBA,PF,6.0,153.0,15.3,0.596,0.000,...,NaN,0.2,0.3,0.5,0.144,NaN,-1.0,2.0,0.9,0.1
1,2010-11,21.0,OKC,NBA,PF,17.0,490.0,15.2,0.514,0.007,...,NaN,0.5,0.6,1.1,0.109,NaN,-1.6,0.8,-0.8,0.1
2,2011-12,22.0,OKC,NBA,PF,20.0,569.0,18.9,0.558,0.025,...,NaN,1.4,0.5,1.8,0.155,NaN,0.9,1.5,2.4,0.6
3,2012-13,23.0,OKC,NBA,PF,11.0,366.0,17.1,0.484,0.067,...,NaN,0.5,0.5,1.0,0.131,NaN,0.9,-0.1,0.8,0.3
4,2013-14,24.0,OKC,NBA,PF,17.0,581.0,16.6,0.633,0.088,...,NaN,1.0,0.7,1.7,0.143,NaN,1.1,1.7,2.8,0.7
5,2015-16,26.0,OKC,NBA,PF,18.0,602.0,15.3,0.629,0.423,...,NaN,1.4,0.7,2.0,0.163,NaN,2.1,1.5,3.6,0.9
6,2016-17,27.0,TOR,NBA,PF,10.0,307.0,14.4,0.527,0.292,...,NaN,0.0,0.4,0.4,0.065,NaN,-0.5,0.8,0.3,0.2
7,2017-18,28.0,TOR,NBA,PF,10.0,260.0,10.9,0.533,0.333,...,NaN,0.0,0.0,0.1,0.014,NaN,-1.7,-0.4,-2.2,0.0
8,2018-19,29.0,TOR,NBA,C,24.0,500.0,15.0,0.532,0.197,...,NaN,0.4,0.8,1.2,0.114,NaN,-1.6,1.2,-0.4,0.2
9,2019-20,30.0,TOR,NBA,C,11.0,251.0,25.2,0.702,0.409,...,NaN,0.8,0.5,1.3,0.250,NaN,5.2,2.6,7.7,0.6
10,2020-21,31.0,LAC,NBA,C,2.0,18.0,30.7,0.644,0.333,...,NaN,0.1,0.0,0.1,0.285,NaN,5.0,7.0,12.0,0.1
11,2021-22,32.0,MIL,NBA,C,6.0,22.0,-3.9,0.267,0.188,...,NaN,-0.2,0.0,-0.2,-0.355,NaN,-13.3,-7.7,-21.1,-0.1
12,Career,NaN,NaN,NBA,NaN,152.0,4119.0,16.3,0.564,0.188,...,NaN,6.0,5.1,11.1,0.130,NaN,0.4,1.1,1.5,3.6
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,6 seasons,NaN,OKC,NBA,NaN,89.0,2761.0,16.5,0.567,0.122,...,NaN,5.0,3.2,8.2,0.142,NaN,0.7,1.2,1.9,2.7
15,4 seasons,NaN,TOR,NBA,NaN,55.0,1318.0,16.0,0.567,0.287,...,NaN,1.1,1.9,3.0,0.109,NaN,-0.1,1.0,1.0,1.0
16,1 season,NaN,MIL,NBA,NaN,6.0,22.0,-3.9,0.267,0.188,...,NaN,-0.2,0.0,-0.2,-0.355,NaN,-13.3,-7.7,-21.1,-0.1
17,1 season,NaN,LAC,NBA,NaN,2.0,18.0,30.7,0.644,0.333,...,NaN,0.1,0.0,0.1,0.285,NaN,5.0,7.0,12.0,0.1

# Store this data Into CSV Format

In [65]:
df4[3].to_csv('Web_player3_data.csv')

# Create all Table in my dir

In [67]:
html_data = pd.read_html('https://www.basketball-reference.com/players/i/ibakase01.html')
for i in range(len(html_data)):
    html_data[i].to_csv(f'html_data{i}.csv',index = False)

In [85]:
pd.read_json("https://api.github.com/repos/pandas-dev/pandas/issues")

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59745,2511762879,PR_kwDOAA0YD856vKCn,59745,API: value_counts to consistently maintain ord...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #59307 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59744,2511651388,PR_kwDOAA0YD856uwsp,59744,"Doc string for pandas.Timestamp.max, pandas.Ti...",...,NaT,NONE,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,Context in https://github.com/pandas-dev/panda...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59743,2511444769,PR_kwDOAA0YD856uHfq,59743,BUG: Remove `read_json` datetime deprecation w...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #59511 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59742,2511368604,PR_kwDOAA0YD856t24H,59742,DOCS: fix docstring validation errors for grou...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Address issues like #56804\r\n\r\nFixes docstr...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59741,2511332805,PR_kwDOAA0YD856tvcu,59741,DOC: Fix SA01 for pandas.Series.dt.nanoseconds...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Adds See Also & Extended Summary for:\r\n`pand...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59739,2510768152,I_kwDOAA0YD86Vp0gY,59739,BUG: FutureWarning for Boolean sparse dtypes i...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59738,2510767093,I_kwDOAA0YD86Vp0P1,59738,BUG: fixed_size_list pyarrow type not interpre...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59737,2510621084,I_kwDOAA0YD86VpQmc,59737,ENH: DataFrame.from_dict doesn't work with col...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59736,2510587701,I_kwDOAA0YD86VpIc1,59736,"BUG: pd.eval with engine=""numexpr"" fails with ...",...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59732,2509689900,I_kwDOAA0YD86VltQs,59732,BUG: df.loc astype type change on specific row...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59729,2509443198,PR_kwDOAA0YD856nVGm,59729,"DOC: fix SA01,ES01 for pandas.RangeIndex.stop",...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,fixes\r\n\r\n```\r\npandas.RangeIndex.stop SA0...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59728,2509415886,PR_kwDOAA0YD856nO-t,59728,"DOC: fix SA01,ES01 for pandas.RangeIndex.start",...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,fixes\r\n\r\n```\r\npandas.RangeIndex.start SA...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59725,2508796032,I_kwDOAA0YD86ViTCA,59725,ENH: Should groupby's `value_counts` sorts on ...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59724,2508738272,PR_kwDOAA0YD856k7Im,59724,BUG (string): Series.str.slice with negative step,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #59710 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59722,2508558388,PR_kwDOAA0YD856kTbp,59722,Fix part of docstring timedelta #59698,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Part of [59698](https://github.com/pandas-dev/...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59721,2508391458,I_kwDOAA0YD86VgwQi,59721,BUG: `pd.read_html(...)`: Unable to handle mal...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59720,2508099944,PR_kwDOAA0YD856iu--,59720,"BUG: CSS strings truncated at "":""",...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Fixes issue #59623 \r\n\r\nChanges `maybe_conv...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59719,2507686865,PR_kwDOAA0YD856hTzu,59719,"Fix docstring Timedelta.to_timedelta64 SA01, T...",...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Issue #59698\r\n\r\nSolved the following \r\n`...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59717,2507322136,I_kwDOAA0YD86VcrMY,59717,BUG: DataFrame.from_records()'s columns argume...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59716,2507147125,I_kwDOAA0YD86VcAd1,59716,QST: DataFrame.plot() vs Series.plot() have in...,...,NaT,NONE,NaN,NaN,NaN,### Research\n\n- [X] I have searched the [[pa...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59715,2506888795,I_kwDOAA0YD86VbBZb,59715,QST: Consistently apply Welford Method and Kah...,...,NaT,NONE,NaN,NaN,NaN,### Research\n\n- [X] I have searched the [[pa...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59714,2506598139,PR_kwDOAA0YD856dnN8,59714,fixed issue#59670. DOC,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #59670 \r\n\r\n,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59712,2506466832,I_kwDOAA0YD86VZaYQ,59712,BUG: groupby().any() returns True instead of F...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59711,2506452193,I_kwDOAA0YD86VZWzh,59711,BUG: converting null timedelta to int with ast...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59710,2506436697,I_kwDOAA0YD86VZTBZ,59710,API/BUG: obj.str.slice(start:None:-1),...,NaT,MEMBER,NaN,NaN,NaN,```python\r\nimport pandas as pd\r\nimport pya...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59700,2503675229,PR_kwDOAA0YD856TnkJ,59700,DOC: fix broken link for governance in the tea...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #59693 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59697,2503532629,I_kwDOAA0YD86VOOBV,59697,BUG: DataFrame.stack does not work when column...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59696,2503323754,PR_kwDOAA0YD856SbUR,59696,ENH: add basic DataFrame.from_arrow class meth...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,See https://github.com/pandas-dev/pandas/issue...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59694,2502994789,I_kwDOAA0YD86VMKtl,59694,BUG: memory leak when using read_csv with pyth...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59693,2502707419,I_kwDOAA0YD86VLEjb,59693,DOC: broken link for governance in the team we...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN